version: "3.9"

services:
  app:
    build: .
    container_name: telegram_bot_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "503:8081"
  #   env_file:
  #     - .env
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST}
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
  #     - ME_CONFIG_MONGODB_URL=${MONGODB_URI}
  #     - ME_CONFIG_OPTIONS_EDITORTHEME=${ME_CONFIG_OPTIONS_EDITORTHEME}